name: SpaceTags
main: com.nametagedit.plugin.NametagEdit
version: 4.4.14
authors: [sgtcaze, Cory, Plugner]
soft-depend: [zPermissions, PermissionsEX, GroupManager, LuckPerms, LibsDisguises, Guilds, PlaceholderAPI]
commands:
  st:
    description: Comandos do SpaceTags
    aliases: [stags]
